#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


repos:

# Refresh the Python virtual environment
- repo: local
  hooks:
    - id: build
      name: refresh_environment
      entry: ./invoke.sh sync
      language: script
      pass_filenames: false
      always_run: true

# Check license headers and white space vs tabs
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: forbid-crlf
    - id: forbid-tabs
    - id: remove-tabs
      args: [--whitespaces-count, '2']  # defaults to: 4
    - id: insert-license
      files: \.(py|tf)$
      args:
        - --license-filepath
        - docs/LICENSE_HEADER.txt # defaults to: LICENSE.txt
        - --no-extra-eol          # see below

# Apply pylint
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: ./run.sh pylint
#       language: script
#       require_serial: true
#       files: ^.*/src/.*\.py$

# Apply pyright
- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: ./run.sh pyright --pythonpath=.venv/bin/python3
      language: script
      require_serial: true
      files: ^.*/src/.*\.py$

# Format the terraform
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.88.4
#   hooks:
#     - id: terraform_fmt
