---
ignored:
  - DL3059 # "multiple conservutive RUN commands, consider consolidation" https://github.com/hadolint/hadolint/wiki/DL3059
  - DL3022 # COPY --from should reference a previously defined FROM alias" https://github.com/hadolint/hadolint/wiki/DL3059
