# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
extends: default

locale: "en_US.UTF-8"

rules:
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
    min-spaces-inside: 1
    min-spaces-inside-empty: 0
  colons:
    max-spaces-after: 1
  comments:
    # As required by prettier
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start:
    level: error
  empty-values: enable
  line-length:
    allow-non-breakable-inline-mappings: true
    max: 250
  octal-values: enable
  truthy:
    level: error
