[project]
name = "processor-web-ui"
version = "0.0.1.dev"
dependencies = [
    "fastapi",
    "uvicorn",
    "fireo",
    "google-api-core",
    "google-cloud-storage",
    "google-cloud-logging",
    "google-cloud-bigquery",
]
